<a href="https://colab.research.google.com/github/VitalyGladyshev/NeuroN/blob/master/HW_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ДЗ_03

In [1]:
import numpy as np
import pandas as pd

import tensorflow as tf

!pip install -q tensorflow-hub
!pip install -q tensorflow-datasets
import tensorflow_hub as hub
import tensorflow_datasets as tfds

In [2]:
from typing import List, Tuple

In [3]:
def calculate_confidence_interval(scores: list, conf_interval: float = 0.95) -> Tuple[float]:
    """
    Вычисление доверительного интервала.

    Parameters
    ----------
    scores: List[float / int]
        Список с оценками изучаемой величины.

    conf_interval: float, optional, default = 0.95
        Уровень доверия для построения интервала.
        Опциональный параметр, по умолчанию, равен 0.95.

    Returns
    -------
    conf_interval: Tuple[float]
        Кортеж с границами доверительного интервала.

    """
    left_bound = np.percentile(
        scores, ((1 - conf_interval) / 2) * 100
    )
    right_bound = np.percentile(
        scores, (conf_interval + ((1 - conf_interval) / 2)) * 100
    )

    return left_bound, right_bound

# Задание 1
Поработайте с документацией TensorFlow 2. Найти 2-3 полезные команды TensorFlow, не разобранные на уроке (полезные для Вас).

## Типы тензоров

tf.Tensor обладает следующими параметрами:
- тип данных (float32, int32, или string, например)
- размеры (shape)

Основные виды тензоров следующие:
- tf.Variable
- tf.constant
- tf.placeholder
- tf.SparseTensor

Ранг объекта tf.Tensor это количество его измерений. Синонимами ранга являются порядок, степень, размерность. Ранг в TensorFlow это не то же самое, что и ранг матрицы в математике. Как показывает следующая таблица, каждый ранг в Tensorflow соответствует некоторой математической сущности:

- 0	Скаляр (только величина)
- 1	Вектор (величина и направление)
- 2	Матрица (таблица чисел)
- 3	3-Тензор (куб чисел)
- n	n-Тензор
### Ранг 0

In [4]:
mammal = tf.Variable("Elephant", tf.string)
mammal

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Elephant'>

In [5]:
ignition = tf.Variable(451, tf.int16)
ignition

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=451>

In [6]:
floating = tf.Variable(3.14159265359, tf.float64)
floating

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.1415927>

In [7]:
its_complicated = tf.Variable(12.3 - 4.85j, tf.complex64)
its_complicated

<tf.Variable 'Variable:0' shape=() dtype=complex128, numpy=(12.3-4.85j)>

### Ранг 1

In [8]:
mystr = tf.Variable(["Hello"], tf.string)
cool_numbers  = tf.Variable([3.14159, 2.71828], tf.float32)
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32)
its_very_complicated = tf.Variable([12.3 - 4.85j, 7.5 - 6.23j], tf.complex64)
its_very_complicated

<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([12.3-4.85j,  7.5-6.23j])>

### Ранг 2

In [9]:
mymat = tf.Variable([[7],[11]], tf.int16)
mymat

<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
array([[ 7],
       [11]], dtype=int32)>

In [10]:
myxor = tf.Variable([[False, True],[True, False]], tf.bool)
myxor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=bool, numpy=
array([[False,  True],
       [ True, False]])>

In [11]:
linear_squares = tf.Variable([[4], [9], [16], [25]], tf.int32)
linear_squares

<tf.Variable 'Variable:0' shape=(4, 1) dtype=int32, numpy=
array([[ 4],
       [ 9],
       [16],
       [25]], dtype=int32)>

In [12]:
squarish_squares = tf.Variable([[4, 9], [16, 25]], tf.int32)
squarish_squares

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[ 4,  9],
       [16, 25]], dtype=int32)>

In [13]:
rank_of_squares = tf.rank(squarish_squares)
rank_of_squares

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [14]:
mymatC = tf.Variable([[7],[11]], tf.int32)
mymatC

<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
array([[ 7],
       [11]], dtype=int32)>

### Ранги более высокого порядка

Тензоры более высокого ранга, аналогично, состоят из n-мерных массивов.

In [15]:
my_image = tf.zeros([2, 3, 4, 5])  # размер пакета x высота x ширина x количество цветовых каналов
my_image

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

Получение ранга объекта tf.Tensor

In [16]:
r = tf.rank(my_image)
r

<tf.Tensor: shape=(), dtype=int32, numpy=4>

### Индексация и срезы

In [17]:
first_primes

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 2,  3,  5,  7, 11], dtype=int32)>

In [18]:
my_scalar = first_primes[2]
my_scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [19]:
squarish_squares

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[ 4,  9],
       [16, 25]], dtype=int32)>

In [20]:
my_scalar = squarish_squares[1, 1]
my_scalar

<tf.Tensor: shape=(), dtype=int32, numpy=25>

In [21]:
my_row_vector = squarish_squares[1]
my_row_vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([16, 25], dtype=int32)>

In [22]:
my_column_vector = squarish_squares[:, 1]
my_column_vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 9, 25], dtype=int32)>

## Размеры

Размеры тензора это количество элементов в каждом измерении. Документация TensorFlow использует три условных обозначения для описания размерности тензора: ранг, размеры и количество измерений. Следующая таблица показывает как они соотносятся друг с другом:

- 0	[]	0-D	0-D тензор. Скаляр
- 1	[D0]	1-D	1-D тензор размера [5]
- 2	[D0, D1]	2-D	2-D тензор размера [3, 4]
- 3	[D0, D1, D2]	3-D	3-D тензор размера [1, 4, 3]
- n	[D0, D1,… Dn-1]	n-D	Тензор размера [D0, D1,… Dn-1]

Размеры могут быть представлены в виде списков Python/кортежей целых чисел, или с помощью
tf.TensorShape

In [23]:
my_image.shape

TensorShape([2, 3, 4, 5])

### Изменение размеров tf.Tensor

Количество элементов тензора это произведение всех его измерений. Количество элементов скаляра всегда равно 1. Так как много разных размеров могут давать одно и то же число элементов часто удобно менять размеры tf.Tensor, не изменяя его элементы. Это может быть сделано с помощью tf.reshape.

In [24]:
rank_three_tensor = tf.ones([3, 4, 5])
rank_three_tensor

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [25]:
matrix = tf.reshape(rank_three_tensor, [6, 10])  # Преобразование существущих данных
                                                 # в матрицу 6x10 
matrix

<tf.Tensor: shape=(6, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [26]:
matrixB = tf.reshape(matrix, [3, -1])  # Преобразование существующих данных в 
                                       # матрицу 3x20. -1 говорит reshape что нужно
                                       # посчитать размер этого измерения.
matrixB

<tf.Tensor: shape=(3, 20), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]], dtype=float32)>

In [27]:
matrixAlt = tf.reshape(matrixB, [4, 3, -1])  # Преобразование существующих данных в
                                             # тензор 4x3x5

matrixAlt

<tf.Tensor: shape=(4, 3, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

Число элементов в преобразованных тензорах  должно совпадать с изначальным количеством. Поэтому следующий пример породит ошибку поскольку нет такого значения для последнего измерения при котором совпадет количество элементов.

In [28]:
yet_another = tf.reshape(matrixAlt, [13, 2, -1])  # ERROR!

InvalidArgumentError: ignored

## Типы данных

В дополнение к размерности, у тензоров есть тип данных. У конкретного tf.Tensor не может быть более одного типа данных. Однако, возможно сериализовать произвольные структуры данных в string и хранить их в tf.Tensor.

Можно преобразовать tf.Tensor из одного типа данных в другой используя tf.cast.

Преобразование константного целочисленного тензора в тензор с плавающей запятой.

In [29]:
float_tensor = tf.cast(tf.constant([1, 2, 3]), dtype=tf.float32)

In [30]:
float_tensor.dtype

tf.float32

При создании tf.Tensor из объекта python можно опционально указать тип данных. Если вы этого не сделаете, TensorFlow выберет тип данных который может представлять ваши данные. TensorFlow преобразует целые числа Python в tf.int32, а числа с плавающей запятой в tf.float32. В других случаях TensorFlow использует те же правила что и numpy при конвертации массивов.

# Задание 2

Попробуйте обучить нейронную сеть на TensorFlow 2 на датасете imdb_reviews. Опишите, какого результата вы добились от нейросети? Что помогло вам улучшить ее точность?

Попробуйте улучшить работу нейронной сети(меняем число слоев, число нейронов, типы активации, тип оптимизатора). Постройте 10-15 вариантов и сведите результаты их работы в таблицу

In [31]:
train_data, validation_data, test_data = tfds.load(
    name="imdb_reviews", 
    split=('train[:60%]', 'train[60%:]', 'test'),
    as_supervised=True)

Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteU437NE/imdb_reviews-train.tfrecord


Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteU437NE/imdb_reviews-test.tfrecord


Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0.incompleteU437NE/imdb_reviews-unsupervised.tfrecord


Dataset imdb_reviews downloaded and prepared to /root/tensorflow_datasets/imdb_reviews/plain_text/1.0.0. Subsequent calls will reuse this data.


In [32]:
embedding = "https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1"
hub_layer = hub.KerasLayer(embedding, input_shape=[], 
                           dtype=tf.string, trainable=True)

## Базовый вариант

In [33]:
model = tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(1))

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
keras_layer (KerasLayer)     (None, 20)                400020    
_________________________________________________________________
dense (Dense)                (None, 16)                336       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 17        
Total params: 400,373
Trainable params: 400,373
Non-trainable params: 0
_________________________________________________________________


In [34]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [35]:
history = model.fit(train_data.shuffle(10000).batch(512),
                    epochs=10,
                    validation_data=validation_data.batch(512),
                    verbose=1)

Epoch 1/10
30/30 [==============================] - 2s 81ms/step - loss: 0.7068 - accuracy: 0.5109 - val_loss: 0.6673 - val_accuracy: 0.5111
Epoch 2/10
30/30 [==============================] - 2s 76ms/step - loss: 0.6456 - accuracy: 0.5281 - val_loss: 0.6269 - val_accuracy: 0.5643
Epoch 3/10
30/30 [==============================] - 2s 75ms/step - loss: 0.6012 - accuracy: 0.6060 - val_loss: 0.5857 - val_accuracy: 0.6251
Epoch 4/10
30/30 [==============================] - 2s 76ms/step - loss: 0.5586 - accuracy: 0.6740 - val_loss: 0.5456 - val_accuracy: 0.6855
Epoch 5/10
30/30 [==============================] - 2s 76ms/step - loss: 0.5147 - accuracy: 0.7308 - val_loss: 0.5038 - val_accuracy: 0.7337
Epoch 6/10
30/30 [==============================] - 2s 78ms/step - loss: 0.4700 - accuracy: 0.7668 - val_loss: 0.4675 - val_accuracy: 0.7564
Epoch 7/10
30/30 [==============================] - 2s 76ms/step - loss: 0.4286 - accuracy: 0.7981 - val_loss: 0.4354 - val_accuracy: 0.7995
Epoch 8/10
30

In [36]:
results = model.evaluate(test_data.batch(512), verbose=2)

for name, value in zip(model.metrics_names, results):
    print("%s: %.3f" % (name, value))

49/49 - 2s - loss: 0.3758 - accuracy: 0.8209
loss: 0.376
accuracy: 0.821


## Генерация сетей и перебор параметров

In [37]:
def net_gen(func='relu', lay_cnt=1, neurons=16):
    model = tf.keras.Sequential()
    model.add(hub_layer)
    model.add(tf.keras.layers.Dense(neurons, activation=func))
    if not lay_cnt==1:
        model.add(tf.keras.layers.Dense(neurons, activation=func))
    model.add(tf.keras.layers.Dense(1))
    
    model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

    return model

In [38]:
def net_iter(model, ep=10, batch_size=512):
    history = model.fit(train_data.shuffle(10000).batch(batch_size),
                epochs=ep,
                validation_data=validation_data.batch(batch_size),
                verbose=0)
    return history.history

In [39]:
summary_data = pd.DataFrame(data=[[0, 0, 0, 0, 0, 0, 0, 0, 0]], 
                            columns=['func', 'batch', 'layers', 'neurons', 'mean_train_accuracy', 'mean_val_accuracy', 'variance', 'l_b', 'r_b'])
cnt = 0
fc = ['relu', 'sigmoid']
b_s = [256, 512]
l_c = [1, 2]
nr = [16, 32]
epochs = 10

# net_res = []

for fc_i in fc:
    for b_s_i in b_s:
        for l_c_i in l_c:
            for nr_i in nr:
                err_accuracy = []
                err_val_accuracy = []
                print(f"Модель: функция {fc_i}, батч {b_s_i}, слоёв {l_c_i}, нейронов {nr_i}, эпох {epochs}\n")
                model = net_gen(func=fc_i, lay_cnt=l_c_i, neurons=nr_i)
                model.summary()
                for i in range(6):
                    print(f"\tИтерация: {i+1}")
                    hist = net_iter(model, batch_size=b_s_i, ep=epochs)
                    # net_res.append(hist)
                    err_accuracy.append(hist['accuracy'][-1])
                    err_val_accuracy.append(hist['val_accuracy'][-1])

                vr = np.var(err_val_accuracy)
                l_b, r_b = calculate_confidence_interval(err_val_accuracy)
                mean_err_accuracy, mean_err_val_accuracy = np.mean(err_accuracy), np.mean(err_val_accuracy)
                print(f"Ошибки на train. Средняя: {mean_err_accuracy} список: {err_accuracy}")
                print(f"Ошибки на valid. Средняя: {mean_err_val_accuracy} список: {err_val_accuracy}")
                print(f"Дисперсия ошибки на valid: {vr}")
                print(f"Доверительный интервал: {l_b} - {r_b}\n\n")
                summary_data.loc[cnt, ['func', 'batch', 'layers', 'neurons', 'mean_train_accuracy', 
                                       'mean_val_accuracy', 'variance', 'l_b', 'r_b']] = [fc_i, 
                                        b_s_i, l_c_i, nr_i, np.mean(err_accuracy), 
                                        np.mean(err_val_accuracy), vr, l_b, r_b]
                cnt += 1

Модель: функция relu, батч 256, слоёв 1, нейронов 16 эпох 10

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
keras_layer (KerasLayer)     (None, 20)                400020    
_________________________________________________________________
dense_2 (Dense)              (None, 16)                336       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 17        
Total params: 400,373
Trainable params: 400,373
Non-trainable params: 0
_________________________________________________________________
	Итерация: 1
	Итерация: 2
	Итерация: 3
	Итерация: 4
	Итерация: 5
	Итерация: 6
Ошибки на train. Средняя: 0.9809888899326324 список: [0.9201333522796631, 0.9725333452224731, 0.9936666488647461, 0.9995999932289124, 1.0, 1.0]
Ошибки на valid. Средняя: 0.8622333208719889 список: [0.8677999973297119, 0.8679999709129333, 

In [40]:
summary_data

func  batch  layers  ...      variance       l_b       r_b
0      relu  256.0     1.0  ...  2.594550e-05  0.855950  0.867975
1      relu  256.0     1.0  ...  5.556693e-06  0.853850  0.860638
2      relu  256.0     2.0  ...  6.847044e-07  0.854512  0.856687
3      relu  256.0     2.0  ...  7.055506e-07  0.854363  0.856725
4      relu  512.0     1.0  ...  2.598073e-06  0.856300  0.860338
5      relu  512.0     1.0  ...  3.738071e-06  0.855212  0.860338
6      relu  512.0     2.0  ...  4.788909e-07  0.857450  0.859413
7      relu  512.0     2.0  ...  5.404648e-06  0.854350  0.860312
8   sigmoid  256.0     1.0  ...  7.192476e-06  0.857550  0.864450
9   sigmoid  256.0     1.0  ...  3.968065e-06  0.856750  0.862100
10  sigmoid  256.0     2.0  ...  5.955572e-07  0.861200  0.863225
11  sigmoid  256.0     2.0  ...  3.113886e-07  0.859950  0.861588
12  sigmoid  512.0     1.0  ...  2.196684e-06  0.860725  0.864850
13  sigmoid  512.0     1.0  ...  2.684715e-06  0.861075  0.865237
14  sigmoid  512.0     2.0  ...  9.655786e-07  0.862050  0.864850
15  sigmoid  512.0     2.0  ...  9.533378e-07  0.860738  0.863350

[16 rows x 9 columns]

In [51]:
summary_data.loc[:, 'mean_val_accuracy'].sort_values(ascending=False)

14    0.863067
13    0.862883
12    0.862500
0     0.862233
10    0.861833
15    0.861500
11    0.860617
8     0.860150
9     0.858517
6     0.858133
4     0.858117
1     0.856900
5     0.856883
7     0.856317
3     0.855533
2     0.855117
Name: mean_val_accuracy, dtype: float64

In [53]:
summary_data.sort_values('mean_val_accuracy', ascending=False)

func  batch  layers  ...      variance       l_b       r_b
14  sigmoid  512.0     2.0  ...  9.655786e-07  0.862050  0.864850
13  sigmoid  512.0     1.0  ...  2.684715e-06  0.861075  0.865237
12  sigmoid  512.0     1.0  ...  2.196684e-06  0.860725  0.864850
0      relu  256.0     1.0  ...  2.594550e-05  0.855950  0.867975
10  sigmoid  256.0     2.0  ...  5.955572e-07  0.861200  0.863225
15  sigmoid  512.0     2.0  ...  9.533378e-07  0.860738  0.863350
11  sigmoid  256.0     2.0  ...  3.113886e-07  0.859950  0.861588
8   sigmoid  256.0     1.0  ...  7.192476e-06  0.857550  0.864450
9   sigmoid  256.0     1.0  ...  3.968065e-06  0.856750  0.862100
6      relu  512.0     2.0  ...  4.788909e-07  0.857450  0.859413
4      relu  512.0     1.0  ...  2.598073e-06  0.856300  0.860338
1      relu  256.0     1.0  ...  5.556693e-06  0.853850  0.860638
5      relu  512.0     1.0  ...  3.738071e-06  0.855212  0.860338
7      relu  512.0     2.0  ...  5.404648e-06  0.854350  0.860312
3      relu  256.0     2.0  ...  7.055506e-07  0.854363  0.856725
2      relu  256.0     2.0  ...  6.847044e-07  0.854512  0.856687

[16 rows x 9 columns]

# Выводы

Лучшие средние значения на valid выборке показали сети с функцией активации sigmoid, размером батча 512. Топологии: 1 слой с 32 нейронами или 2 слоя с 16 нейронами